baseurl = "/"
title = "Leetcoding"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "binario"
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
  name = "Holten KO"
  bio = "Make your own way."
  avatar = "img/avatar.png"

[Params]
  description = "Responsive card-based & code-light Hugo theme" # Site Description. Used in meta description
  copyright = "" # Copyright holder, otherwise will use .Site.Title
  opengraph = true # Enable OpenGraph if true
  columns = 2 # Set the number of cards columns. Possible values: 1, 2, 3
  mainSections = ["post"] # Set main page sections
  post_meta = ["date", "categories"] # Enable post meta fields in given order
  dateFormat = "January 02, 2006" # Change the format of dates
  colorTheme = "light-gray" # dark-green, dark-blue, dark-red, dark-violet
  mainMenuAlignment = "right" # Align main menu (desktop version) to the right side
  authorbox = true # Show authorbox at bottom of single pages if true
  tocOpen = true # Open Table of Contents block. Optional
  mathjax = true # Enable MathJax for all site pages
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path. Optional
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config. Optional
  hideNoPostsWarning = false # Don't show no posts empty state warning in main page, if true

[Menus]
  [[Menus.main]]
    name       = "About"
    url        = "about/"
  [[Menus.main]]
    name       = "Blog"
    url        = "/blog"